### ISSUE TITLE
Dataverse on Azure

### ISSUE THREAD

**Issue by 4tikhonov** [GlobalDataverseCommunityConsortium/dataverse-kubernetes#108]
Hi @poikilotherm and @pdurbin, I've just managed to deploy Dataverse on Kubernetes cluster provided by Microsoft Azure.

The good news that infrastructure works without any modifications with kubectl higher than 1.14 (with kustomize support)! The only difference is the specification for volume claims, it's different for S3, Google Cloud and (now) Azure.

How do you want to get it in the repository?

**Comment by pdurbin** [comment]
I betcha @rc-colabear will be excited! He opened https://github.com/IQSS/dataverse/issues/4247 . I'm excited too. Great work, @4tikhonov 🎉

**Comment by poikilotherm** [comment]
@4tikhonov please be aware that I just released [v4.16](https://github.com/IQSS/dataverse-kubernetes/releases/tag/v4.16) Lots of stuff now inside, many bugfixes.

And yes, it would be really cool to include those. I thought about stealing the term "installation personas" from @pdurbin and provide such things in the repo. See also #91.

For #63 I started to create a folder `k8s/experiments`, maybe we can rename to `k8s/personas` and for this Azure thing we can just provide a cool kustomization.yaml file with the necessary patches?

**Comment by pdurbin** [comment]
Credit to @janetm for the idea of Dataverse installation personas. Just wait till you see her poster! 😄

**Comment by 4tikhonov** [comment]
@poikilotherm, I don't think I fully understand the idea. Anyway it does work on Azure with different volumes specification
https://github.com/Dans-labs/dataverse-kubernetes/commit/b50c523bb270d531d2f8b755628869849b94b8aa

I believe we need to put this in kustomization.yaml to be able to choose Cloud Provider between Amazon, Azure and Google Cloud.

**Comment by poikilotherm** [comment]
Hey @4tikhonov are you ok with me doing changes in your branch to showcase what I am up to?

**Comment by 4tikhonov** [comment]
@poikilotherm, just go ahead, OpenShift support is also coming. :)

**Comment by 4tikhonov** [comment]
Hi @poikilotherm, we're working on the manual describing how to deploy Dataverse in Microsoft Azure Cloud. Do you have some progress with kustomization.yaml to get a Cloud as parameter?

**Comment by poikilotherm** [comment]
As #110 has been closed by integrating it within the docs (see 4e0cf5b and http://k8s-docs.gdcc.io/en/v4.20/day1/provider-hints.html), I'll close this issue.

Feel free to re-open if sth. is missing.
