### ISSUE TITLE
Create docs for upstream pointing to this project

### ISSUE THREAD

**Issue by poikilotherm** [GlobalDataverseCommunityConsortium/dataverse-kubernetes#47]
@pdurbin [invited on IRC](http://irclog.iq.harvard.edu/dataverse/2019-04-25#i_91754) to create a PR at IQSS/dataverse to provide an adventure (no dices included) in http://guides.dataverse.org/en/latest/installation/prep.html#choose-your-own-installation-adventure

We should point people to this project, which is still in flux, but worth a try.

This might be a solution to IQSS/dataverse#4665, too... ;-)

**Comment by pdurbin** [comment]
Simply adding the words "community supported" and "experimental" will go a long way toward setting expectations appropriately. Thanks!!

**Comment by poikilotherm** [comment]
Since Dataverse 5.0 (or more precise: IQSS/dataverse#6593), upstream points to this project. Closing.
