### ISSUE TITLE
Ease deployments on different platforms

### ISSUE THREAD

**Issue by poikilotherm** [GlobalDataverseCommunityConsortium/dataverse-kubernetes#81]
Inspired by a video conference with @wilkos-dans @4tikhonov and @pdurbin I thought about providing reusable *[terraform](https://www.terraform.io/)* scripts for cross-plattform deployments.

This could include instructions to setup a K8s cluster and necessary services.

**Comment by pdurbin** [comment]
@joelmarkanderson said, "We are starting to actively develop on the Terraform -> Kubernetes path, and I've begun reconfiguring Docker containers to reflect current dataverse versions. I can let you know more once we have a good sense of scope." at https://github.com/IQSS/dataverse-aws/issues/11#issuecomment-368989741

**Comment by pdurbin** [comment]
I just thought I'd mention that I spotted a new post by @joelmarkanderson over at https://groups.google.com/d/msg/dataverse-community/lr26VTP8lhs/5JoZ-IdnBQAJ

If he has Dataverse on the brain again, it might be a good time to try to draw him into some of our crazy plans. 😄

**Comment by joelmarkanderson** [comment]
We did briefly consider a stint with Terraform, but nothing much came of it. For a while we were running a fragile CloudFormation script that did not age well. We had plans to launch a kubernetes cluster within EC2 space (not provisioned or hosted service) for running the glassfish containers. At the moment we have fallen back to single instance VM until we steady our operations again.

**Comment by pdurbin** [comment]
> We had plans to launch a kubernetes cluster within EC2 space (not provisioned or hosted service) for running the glassfish containers.

Cool. You might be interested in the "Deploy to an Amazon EC2 based custom K8s cluster" doc at https://github.com/IQSS/dataverse-kubernetes/blob/v4.15.1/docs/aws-kops.md

**Comment by poikilotherm** [comment]
I'm closing this as an issue out of scope.
There are just too many options how to create or rent a K8s cluster, so IMHO it's not worth maintaining just another option within this project. This project is about building blocks for Dataverse, not how to do ops for a K8s cluster.
